"""reset db

Revision ID: 482d25a6fc5d
Revises:
Create Date: 2026-05-02 20:00:33.000261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "482d25a6fc5d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("sender", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("recipients", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "church_services",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("service_date", sa.DateTime(), nullable=False),
        sa.Column("speaker", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("service_title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("file_location", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("edited", sa.Boolean(), nullable=False),
        sa.Column("uploaded", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "items",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "media",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("uploaded_on", sa.DateTime(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "members",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("birthday", sa.DateTime(), nullable=False),
        sa.Column("wedding_anniversary", sa.DateTime(), nullable=True),
        sa.Column("baptism_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "test",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("test1", sa.Integer(), nullable=False),
        sa.Column("test2", sa.Integer(), nullable=False),
        sa.Column("test3", sa.Integer(), nullable=False),
        sa.Column("test4", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
        sa.Column("new_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "donation_configs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("frequency", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payments",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column(
            "stripe_payment_intent_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "stripe_subscription_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("donor_email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("donor_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("receipt_url", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("metadata_json", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_payment_intent_id"),
    )
    op.create_table(
        "video_uploads",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("upload_location", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("upload_name", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("media_association_date", sa.DateTime(), nullable=False),
        sa.Column("speaker_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("reference_text", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_uploads")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("test")
    op.drop_table("refresh_tokens")
    op.drop_table("members")
    op.drop_table("media")
    op.drop_table("items")
    op.drop_table("church_services")
    op.drop_table("announcements")
    op.drop_table("payments")
    op.drop_table("donation_configs")
    # ### end Alembic commands ###
