"""payments

Revision ID: e7562edf08a2
Revises: a1b2c3d4e5f6
Create Date: 2026-05-03 08:04:26.845523

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "e7562edf08a2"
down_revision: Union[str, Sequence[str], None] = "482d25a6fc5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refresh_tokens",
        "user_id",
        existing_type=mysql.VARCHAR(length=36),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refresh_tokens",
        "user_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.VARCHAR(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
